export const ActionType = {
    FETCH_MOVIES : 'FETCH_MOVIES',
    SELECT_MOVIE : 'SELECT_MOVIE',
    REMOVE_SELECTED_MOVIE : 'REMOVE_SELECTED_MOVIE',
    SET_CURRENT_PAGE : 'SET_CURRENT_PAGE',
    SET_TOTAL_PAGE : 'SET_TOTAL_PAGE',
    TOGGLE_DARK_MODE : 'TOGGLE_DARK_MODE',
    SET_LOADING_STATUS : 'SET_LOADING_STATUS',
    SET_FILTER_DATA : 'SET_FILTER_DATA',
    SET_TOTAL_MOVIES : 'SET_TOTAL_MOVIES',
    STORE_SEARCH_KEY : 'STORE_SEARCH_KEY',
}